"""update model sizes and relationships

Revision ID: 1eeedaf93694
Revises: 5f4c922a7bc2
Create Date: 2026-03-09 21:35:36.725449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eeedaf93694'
down_revision = '5f4c922a7bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.alter_column('domain_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['domain_name'])

    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.alter_column('is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('question_types', schema=None) as batch_op:
        batch_op.alter_column('type_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('technology',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=30),
               existing_nullable=True)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('subject_code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('subject_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_subject_name_domain', ['subject_name', 'domain_id'])

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('topic_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('topics_topic_name_subject_id_key'), type_='unique')
        batch_op.create_unique_constraint('uq_topic_name_subject', ['topic_name', 'subject_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint('uq_topic_name_subject', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('topics_topic_name_subject_id_key'), ['topic_name', 'subject_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('topic_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint('uq_subject_name_domain', type_='unique')
        batch_op.alter_column('subject_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('subject_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('technology',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('question_types', schema=None) as batch_op:
        batch_op.alter_column('type_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.alter_column('is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('domain_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
