"""Major schema normalization

Revision ID: 55ec81c67869
Revises: ded36a3b7cb2
Create Date: 2026-02-21 22:06:09.511232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55ec81c67869'
down_revision = 'ded36a3b7cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('question_types',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('type_id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('topic_questions',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('topic_id', 'question_id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('questions_topic_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'question_types', ['type_id'], ['type_id'])
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['company_id'])
        batch_op.drop_column('company')
        batch_op.drop_column('type')
        batch_op.drop_column('topic_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type', postgresql.ENUM('problem_statement', 'mcq', 'theoretical', name='question_type_enum'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('company', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('questions_topic_id_fkey'), 'topics', ['topic_id'], ['topic_id'])
        batch_op.drop_column('type_id')
        batch_op.drop_column('company_id')

    op.drop_table('topic_questions')
    op.drop_table('question_types')
    op.drop_table('companies')
    # ### end Alembic commands ###
