"""empty message

Revision ID: 5f4c922a7bc2
Revises: e86df95865c2
Create Date: 2026-03-07 13:33:51.158840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4c922a7bc2'
down_revision = 'e86df95865c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('domain_id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=30),
               existing_nullable=False)

    with op.batch_alter_table('question_types', schema=None) as batch_op:
        batch_op.alter_column('type_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('technology',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=True)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_code', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('domain_id', sa.Integer(), nullable=False))
        batch_op.alter_column('subject_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['subject_code'])
        batch_op.create_foreign_key(None, 'domains', ['domain_id'], ['domain_id'])

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('topic_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('topic_name',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('subject_name',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('domain_id')
        batch_op.drop_column('subject_code')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('technology',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('question_types', schema=None) as batch_op:
        batch_op.alter_column('type_name',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    op.drop_table('domains')
    # ### end Alembic commands ###
