"""intial_migrattion

Revision ID: 787694377932
Revises: 
Create Date: 2026-07-03 22:45:58.362975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787694377932'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('domains',
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('domain_id'),
    sa.UniqueConstraint('domain_name')
    )
    op.create_table('question_types',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('type_id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'superadmin', 'student', 'contributor', name='user_role_enum'), nullable=False),
    sa.Column('authprovider', sa.Enum('local', 'google', name='auth_provider_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('contributor_request',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'revoked', name='request_status_enum'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_string', sa.Text(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['question_types.type_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=6), nullable=False),
    sa.Column('subject_name', sa.String(length=30), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.domain_id'], ),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('subject_code'),
    sa.UniqueConstraint('subject_name', 'domain_id', name='uq_subject_name_domain')
    )
    op.create_table('options',
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('option_id')
    )
    op.create_table('question_occurrences',
    sa.Column('occurrence_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('language', sa.String(length=30), nullable=True),
    sa.Column('technology', sa.String(length=50), nullable=True),
    sa.Column('difficulty_level', sa.Enum('easy', 'medium', 'hard', name='difficulty_level_enum'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('occurrence_id'),
    sa.UniqueConstraint('question_id', 'company_id', 'year', 'language', 'technology', 'difficulty_level', name='uq_question_occurrence')
    )
    op.create_table('topics',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('topic_id'),
    sa.UniqueConstraint('topic_name', 'subject_id', name='uq_topic_name_subject')
    )
    op.create_table('topic_questions',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('topic_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_questions')
    op.drop_table('topics')
    op.drop_table('question_occurrences')
    op.drop_table('options')
    op.drop_table('subjects')
    op.drop_table('questions')
    op.drop_table('contributor_request')
    op.drop_table('users')
    op.drop_table('question_types')
    op.drop_table('domains')
    op.drop_table('companies')
    # ### end Alembic commands ###
